### ISSUE TITLE
CLIPper complains file does not exist while it obviously exists

### ISSUE THREAD

**Issue by algaebrown** [YeoLab/clipper#105]
@byee4 when using CLIPper in modules: `module load clipper/42502ec` this error occurs.
```WARNING: Bind mount '/home/hsher => /home/hsher' overlaps container CWD /home/hsher/scratch/katie_drosphila, may not be available
{'bam': '/home/hsher/scratch/IP-olig-RBFOX2-2.IP-olig-RBFOX2-2_CLIP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam', 'species': 'GRCh38v35noalt', 'outfileF': 'output/CLIPper/katieoligo_RBFOX2_rep2.peaks.bed', 'gene': None, 'minreads': 3, 'poisson_cutoff': 0.05, 'use_global_cutoff': True, 'FDR_alpha': 0.05, 'binom': 0.05, 'threshold': None, 'maxgenes': None, 'np': '16', 'plotit': False, 'verbose': False, 'quiet': False, 'save_pickle': False, 'debug': False, 'max_gap': 15, 'timeout': None, 'premRNA': True, 'gtfFile': None, 'method': 'binomial', 'SloP': True, 'bonferroni_correct': True, 'algorithm': 'spline', 'reverse_strand': False, 'max_width': 75, 'min_width': 50}
Traceback (most recent call last):
  File "/opt/conda/envs/clipper3/bin/clipper", line 33, in <module>
    sys.exit(load_entry_point('clipper==2.1.2', 'console_scripts', 'clipper')())
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.1.2-py3.7-linux-x86_64.egg/clipper/src/main.py", line 266, in call_main
    main(options)
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.1.2-py3.7-linux-x86_64.egg/clipper/src/main.py", line 37, in main
    check_for_index(options.bam)
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.1.2-py3.7-linux-x86_64.egg/clipper/src/utils.py", line 30, in check_for_index
    raise NameError("file %s does not exist" % (bamfile))
NameError: file /home/hsher/scratch/IP-olig-RBFOX2-2.IP-olig-RBFOX2-2_CLIP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam does not exist
```
The path is correct but clipper cannot find it.

Thanks

**Comment by byee4** [comment]
If the file is softlinked, the singularity container may have trouble finding it. Try copying the file to your scratch and see if that fixes it?

**Comment by algaebrown** [comment]
Even I use the original file it does not work `/home/wjin/scratch/CLIP_seq/Kris_Katie/Genome_mapping/IP-olig-RBFOX2-1_eCLIP/results/IP-olig-RBFOX2-1.IP-olig-RBFOX2-1_CLIP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam` it only works when I copy the file to my directory. I think it is because the module/docker does not mount other people's directory (`/home/wjin`)
