### ISSUE TITLE
Exception errors when running pool.py (list index out of range)(SOVLED)

### ISSUE THREAD

**Issue by zhaoshuoxp** [YeoLab/clipper#112]
Hi, I am trying to run current version of clipper  and get the following errors, do you guys have any ideas?

P.S. I have tried conda, guix and docker versions of clipper, same error.

I appreciate any helps!

---------------------------
root@8d35593ec333:/mnt/local/PTBP1# clipper -b PTBP1_1.bam -o PTBP1_1.bed -s mm10 --processors=1
{'bam': 'PTBP1_1.bam', 'species': 'mm10', 'outfileF': 'PTBP1_1.bed', 'gene': None, 'minreads': 3, 'poisson_cutoff': 0.05, 'use_global_cutoff': True, 'FDR_alpha': 0.05, 'binom': 0.05, 'threshold': None, 'maxgenes': None, 'np': '1', 'plotit': False, 'verbose': False, 'quiet': False, 'save_pickle': False, 'debug': False, 'max_gap': 15, 'timeout': None, 'premRNA': True, 'gtfFile': None, 'method': 'binomial', 'SloP': True, 'bonferroni_correct': True, 'algorithm': 'spline', 'reverse_strand': False, 'max_width': 75, 'min_width': 50}
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/envs/clipper3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.1.2-py3.7-linux-x86_64.egg/clipper/src/call_peak.py", line 943, in call_peaks
    interval.stop, strand, "start", False)
  File "clipper/src/readsToWiggle.pyx", line 49, in clipper.src.readsToWiggle.readsToWiggle_pysam
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/clipper3/bin/clipper", line 33, in <module>
    sys.exit(load_entry_point('clipper==2.1.2', 'console_scripts', 'clipper')())
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.1.2-py3.7-linux-x86_64.egg/clipper/src/main.py", line 266, in call_main
    main(options)
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.1.2-py3.7-linux-x86_64.egg/clipper/src/main.py", line 105, in main
    peaks_dicts.append(job.get(timeout=options.timeout))
  File "/opt/conda/envs/clipper3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range

**Comment by zhaoshuoxp** [comment]
The problem has been solved by filtering BAM like samtools view -f2 -F3852
