### ISSUE TITLE
Issue with clipper installation

### ISSUE THREAD

**Issue by elisulvaran** [YeoLab/clipper#119]
Hello. Thank you for creating this tool. I'm trying to use clipper in my local computer but haven't been able to install it. I downloaded the yml file, but when I run the `conda env create -f environment3.yml` line, I get the following error:

    
    Channels:
     - conda-forge
     - bioconda
     - defaults
    Platform: osx-64
    Collecting package metadata (repodata.json): done
    Solving environment: 
    failedPackagesNotFoundError: The following packages are not available from current channels:
    
      - zlib==1.2.11=h7b6447c_3
      - xz==5.2.5=h7b6447c_0
      - tornado==6.0.4=py37h7b6447c_1
      - tk==8.6.10=hbc83047_0
      - sqlite==3.32.3=h62c20be_0
      - sip==4.19.8=py37hf484d3e_0
      - scipy==1.5.0=py37h0b6359f_0
      - scikit-learn==0.23.1=py37h423224d_0
      - readline==8.0=h7b6447c_0
      - qt==5.9.7=h5867ecd_1
      - python==3.7.7=hcff3b4d_5
      - pysam==0.15.3=py37hda2845c_1
      - pyqt==5.9.2=py37h05f1152_2
      - pybedtools==0.8.1=py37h4ef193e_1
      - pcre==8.44=he6710b0_0
      - pandas==1.0.5=py37h0573a6f_0
      - openssl==1.1.1g=h7b6447c_0
      - numpy-base==1.18.5=py37hde5b4d6_0
      - numpy==1.18.5=py37ha1c710e_0
      - ncurses==6.2=he6710b0_1
      - mkl_random==1.1.1=py37h0573a6f_0
      - mkl_fft==1.1.0=py37h23d657b_0
      - mkl-service==2.3.0=py37he904b0f_0
      - mkl==2020.1=217
      - matplotlib-base==3.2.2=py37hef1b27d_0
      - libxml2==2.9.10=he19cac6_1
      - libxcb==1.13=h1bed415_1
      - libuuid==1.0.3=h1bed415_2
      - libstdcxx-ng==9.1.0=hdf63c60_0
      - libssh2==1.9.0=h1ba5d50_1
      - libpng==1.6.37=hbc83047_0
      - libgfortran-ng==7.3.0=hdf63c60_0
      - libgcc-ng==9.1.0=hdf63c60_0
      - libffi==3.3=he6710b0_1
      - libedit==3.1.20191231=h7b6447c_0
      - libdeflate==1.0=h14c3975_1
      - libcurl==7.71.0=h20c2e04_0
      - ld_impl_linux-64==2.33.1=h53a641e_7
      - krb5==1.18.2=h173b8e3_0
      - kiwisolver==1.2.0=py37hfd86e86_0
      - jpeg==9b=h024ee3a_2
      - intel-openmp==2020.1=217
      - icu==58.2=he6710b0_3
      - htseq==0.11.3=py37hb3f55d8_0
      - gstreamer==1.14.0=hb31296c_0
      - gst-plugins-base==1.14.0=hbbd80ab_1
      - glib==2.65.0=h3eb4bd4_0
      - freetype==2.10.2=h5ab3b9f_0
      - fontconfig==2.13.0=h9420a91_0
      - expat==2.2.9=he6710b0_2
      - dbus==1.13.16=hb2f20db_0
      - cython==0.29.20=py37he6710b0_0
      - curl==7.71.0=hbc83047_0
      - bzip2==1.0.8=h7b6447c_0
      - bedtools==2.29.2=hc088bd4_0
    
    Current channels:
    
      - https://conda.anaconda.org/conda-forge/osx-64
      - https://conda.anaconda.org/bioconda/osx-64
      - https://repo.anaconda.com/pkgs/main/osx-64
      - https://repo.anaconda.com/pkgs/r/osx-64
    
    To search for alternate channels that may provide the conda package you're
    looking for, navigate to
    
        https://anaconda.org
    
    and use the search bar at the top of the page.

I tried installing the packages separately but the I get the same error. Any suggestions on how to fix it would be greatly appreciated. Thanks!

**Comment by algaebrown** [comment]
Hi @elisulvaran Elizabeth!
clipper is indeed hard to install. If you are trying to process eCLIP data, I highly recommend skipper
https://github.com/YeoLab/skipper

If you still need clipper, please use the docker
https://hub.docker.com/r/brianyee/clipper

Thanks

**Comment by elisulvaran** [comment]
Hi, 
Thank you very much for the suggestion. I don't have eCLIP data so I'm still trying to use clipper. I followed your suggestion about using it through docker, and I was able to successfully pull the imag, but when I run `docker run brianyee/clipper` I get the following error:
 ```
Traceback (most recent call last):
  File "/opt/conda/bin/clipper", line 11, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/conda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 14, in <module>
    import pybedtools
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/helpers.py", line 13, in <module>
    import pysam
  File "/opt/conda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

I looked into the error and found that libcrypto.so.1.0.0 is under a different name in mac so I tried running it instead in my university server, but when running the command `clipper -b mybam.bam -o out.bed -s hg19` I ran into the same issue. Any ideas on how to resolve this?

Thank you!!

**Comment by byee4** [comment]
Hi, could you please try the "charlene_move_data" tag? It is the last image I built (based off of a branch with relatively recent code: https://github.com/YeoLab/clipper/tree/charlene_move_data)

docker pull brianyee/clipper:charlene_move_data

**Comment by elisulvaran** [comment]
This worked. Thank you very much!
