### ISSUE TITLE
Clip_analysis errors out with TypeError

### ISSUE THREAD

**Issue by shassathe** [YeoLab/clipper#29]
```
processing chromosomes........................
ending phast
file saved
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Traceback (most recent call last):
  File "/home/shsathe/anaconda/bin/clip_analysis", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clip_analysis')()
  File "/home/shsathe/anaconda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/CLIP_analysis_runner.py", line 235, in call_main
    infer=options.infer,
  File "/home/shsathe/anaconda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/CLIP_analysis_runner.py", line 179, in main
    visualize(clusters, extension, outdir)
  File "/home/shsathe/anaconda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/CLIP_analysis_runner.py", line 195, in visualize
    qc_fig = clip_viz.CLIP_QC_figure()
  File "/home/shsathe/anaconda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/CLIP_analysis_display.py", line 907, in CLIP_QC_figure
    self.build_nearest_exon(ax_bar_exontypes)
  File "/home/shsathe/anaconda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/CLIP_analysis_display.py", line 363, in build_nearest_exon
    ind -= .5
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

**Comment by mlovci** [comment]
Change
https://github.com/YeoLab/clipper/blob/master/clipper/src/CLIP_analysis_display.py#L362 <https://github.com/YeoLab/clipper/blob/master/clipper/src/CLIP_analysis_display.py#L362>
to:


```ind = np.arange(5).astype(‘float’)```



Michael Lovci

—————

————

———

——

—

**Comment by shassathe** [comment]
Seems to fix that error, but ended up with a different one at the same point:

```
processing chromosomes........................
ending phast
file saved
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
Index([u'all', u'cds', u'three_prime_utrs', u'five_prime_utrs',
       u'proxintron500', u'distintron500'],
      dtype='object')
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/cds/homerResults/motif5.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/cds/homerResults/motif6.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/cds/homerResults/motif7.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/cds/homerResults/motif8.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/three_prime_utrs/homerResults/motif6.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/three_prime_utrs/homerResults/motif7.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/three_prime_utrs/homerResults/motif8.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/five_prime_utrs/homerResults/motif6.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/five_prime_utrs/homerResults/motif7.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/five_prime_utrs/homerResults/motif8.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/proxintron500/homerResults/motif8.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/distintron500/homerResults/motif7.logo.png
no motif ./homer/293XT_CLIP_RBFOX2_0204_GAGATTCC-TAATCTTA_R1.G07_293XT_CLIP_RBFOX2_0204_RBFOX2.adapterTrim.round2.rmRep.rmDup.sorted.r2.peaks.bed/distintron500/homerResults/motif8.logo.png
/home/shsathe/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py:475: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
/home/shsathe/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:1282: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/home/shsathe/anaconda/lib/python2.7/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
```

**Comment by shassathe** [comment]
Disregard above comment. Closing this issue.

**Comment by mlovci** [comment]
you should leave it open until it's patched

**Comment by algaebrown** [comment]
CLIP analysis is removed from clipper.
