### ISSUE TITLE
getting clipper to run (initial) getting same TypeError as in 9/2015

### ISSUE THREAD

**Issue by sangoc** [YeoLab/clipper#37]
installed to linux using gitclone.
clipper -h shows help file.
I go to run the program and after working out some errors myself, i come to this traceback (see below). the install worked fine and i double checked the dependencies list.  However i have i feeling there is something missing that's not installed, even if it looks like i have all the dependencies. Any thing you can see here to show what i might need, or need to fix? can't get past this point. 

Thanks
-------------------------------------------------------------------------------------------------------
clipper -b merged_FP_1_3.sorted.bam -s mm10 -gtfFile=$GTF -o output.bed -p --superlocal --save-pickle

Traceback (most recent call last):
  File "/home/user/miniconda2/bin/clipper", line 11, in <module>
    sys.exit(call_main())
  File "/home/user/miniconda2/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 687, in call_main
    main(options)
  File "/home/user/miniconda2/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 526, in main
    check_for_index(options.bam)
  File "/home/user/miniconda2/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 47, in check_for_index
    process = call(["samtools", "index", str(bamfile)])
  File "/home/user/miniconda2/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/user/miniconda2/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/home/user/miniconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by gpratt** [comment]
do you have samtools installed?

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by gpratt** [comment]
Alternatively make a index for your bam file manually.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by gpratt** [comment]
Also you don't need the -gtfFile

This is the command I currently use to run clipper

clipper  '-b'
'/home/gpratt/projects/idr/analysis/downsample_v1/553_02_BOP1.merged.r2.05.bam'
'-s' 'hg19'  '-o'
'/home/gpratt/projects/idr/analysis/downsample_v1/553_02_BOP1.merged.r2.05.peaks.bed'
'--bonferroni'  '--superlocal'  '--threshold-method' 'binomial'
'--save-pickle'

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by sangoc** [comment]
OK! that problem was one of calling for the (un)sorted bam and appropriate index instead of the sorted bam.   thanks for your help. 

now i have the same problem as issue #27 
first i had to alter my /dev/shm b/c of a weird python multiprocessing 'permission denied error. When I fixed that (for anyone else with that problem: https://github.com/omniscale/imposm/issues/9 ) I arrive at the same issue raised earlier:

ERROR:root:transcript timed out Expected bytes, got unicode

dependencies automatically installed ok. I'm using  python2.7 same as he had.  Since he had the same problem after manually installing all the dependencies.... i think i might be at the same impasse unless that problem got solved already.   any update with that? something about pybedtools?

**Comment by sangoc** [comment]
added --debug: here's the traceback.  thanks for your help

Traceback (most recent call last):
  File "/home/user/miniconda2/bin/clipper", line 11, in <module>
    sys.exit(call_main())
  File "/home/user/miniconda2/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 687, in call_main
    main(options)
  File "/home/user/miniconda2/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 582, in main
    jobs.append(func_star(job))
  File "/home/user/miniconda2/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 147, in func_star
    return call_peaks(*varables)
  File "/home/user/miniconda2/lib/python2.7/site-packages/clipper/src/call_peak.py", line 901, in call_peaks
    subset_reads = bam_fileobj.fetch(reference=interval.chrom, start=interval.start, end=interval.stop)
  File "pysam/calignmentfile.pyx", line 881, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10856)
  File "pysam/calignmentfile.pyx", line 800, in pysam.calignmentfile.AlignmentFile.parse_region (pysam/calignmentfile.c:10251)
  File "pysam/calignmentfile.pyx", line 1634, in pysam.calignmentfile.AlignmentFile.gettid (pysam/calignmentfile.c:18070)
  File "pysam/calignmentfile.pyx", line 653, in pysam.calignmentfile.AlignmentFile.get_tid (pysam/calignmentfile.c:8720)
  File "pysam/cutils.pyx", line 113, in pysam.cutils.force_bytes (pysam/cutils.c:2622)
TypeError: Expected bytes, got unicode

**Comment by sangoc** [comment]
does there need to be mm10 data in data/regions? in the current build there isn't any.  not sure if that could be an issue.    i get the above error and an empty peaks file

**Comment by sangoc** [comment]
OK for all who are getting this error still...  I installed using pip install ... don't do that.  apparently that pulls from a previous buggy version.
