### ISSUE TITLE
KeyError: 'padj'

### ISSUE THREAD

**Issue by ShanSabri** [YeoLab/clipper#40]
```
[ssabri@n2239 fastq]$ clipper -b ATC.trimmed.uniq.sort.bam -s mm9 --premRNA --verbose --outfile GTT.trimmed.uniq.bed
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.3/bin/clipper", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 674, in call_main
    main(options)
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 611, in main
    options.min_width)
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 491, in filter_results
    final_result = peaks[peaks['padj'] < poisson_cutoff]
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pandas/core/frame.py", line 1992, in __getitem__
    return self._getitem_column(key)
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pandas/core/frame.py", line 1999, in _getitem_column
    return self._get_item_cache(key)
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pandas/core/generic.py", line 1345, in _get_item_cache
    values = self._data.get(item)
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pandas/core/internals.py", line 3225, in get
    loc = self.items.get_loc(item)
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pandas/indexes/base.py", line 1878, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4027)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3891)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12408)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12359)
KeyError: 'padj'
```

Any help would be greatly appreciated.

**Comment by ShanSabri** [comment]
Solved by using `--bonferroni` flag
