### ISSUE TITLE
Warnings with sort depreciation 

### ISSUE THREAD

**Issue by ShanSabri** [YeoLab/clipper#41]
```
[ssabri@n2239 fastq]$ clipper -b ATC.trimmed.uniq.sort.bam -s mm9 --premRNA --bonferroni --outfile GTT.trimmed.uniq.bed
WARNING:py.warnings:/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py:446: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort("final_p_value")

WARNING:py.warnings:/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py:449: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df['padj'] = df.sort("final_p_value", ascending=False).bh_corrected.cummin()

WARNING:py.warnings:/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py:450: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  return df.sort()

```

**Comment by lufeng891109** [comment]
Hi, have you solved the problem? Why it has the warnings?

**Comment by ernstki** [comment]
Hello from 2020!

It's likely that `pip install`ing CLIPper nowadays will bring in a version of pandas that has **already removed** `.sort` (due to the open-ended version specification in [`setup.py`](../blob/master/setup.py#L28)) , producing a traceback like this:

```
Traceback (most recent call last):
  File "/path/to/bin/clipper", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/path/to/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 674, in call_main
    main(options)
  File "/path/to/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 611, in main
    options.min_width)
  File "/path/to/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 487, in filter_results
    peaks = bh_correct(peaks)
  File "/path/to/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 446, in bh_correct
    df = df.sort("final_p_value")
  File "/path/to/lib/python2.7/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'
```

It's also likely that, without the use of a virtual environment to contain CLIPper and its dependencies, some _other_ package will eventually pull in a newer version of pandas as a dependency and break the `clipper` package.

It looks like pandas _removed_ `.sort` entirely [around release 0.20](https://stackoverflow.com/a/44123892/785213). As a workaround, you can install `clipper` into a [virtual environment](https://virtualenv.pypa.io/en/stable/user_guide.html#introduction), then remove and re-install an older version of`pandas`:

```
source venv/bin/active  # don't forget to activate the virtualenv
pip remove pandas
pip install 'pandas==0.19.*'
```

You will likely still have problems, though; newer versions of `scikit-learn` have also created a [deprecation problem](https://stackoverflow.com/a/49376863/785213) of their own, at version 0.18. There may be other dependencies that are "too new" as well; our lab is still working through these.

Theoretically, though, the same technique as above could be used to arrive at a set of packages installed in a virtual environment that satisfy `clipper`'s requirements.
