### ISSUE TITLE
ValueError: Cannot set a frame with no defined index (..pandas related)

### ISSUE THREAD

**Issue by ShanSabri** [YeoLab/clipper#43]
```
shans-clust:chr1 shansabri$ clipper -b ATC.trimmed.uniq.MAPPED.chr1.sort.bam -s mm9 --premRNA --bonferroni --outfile ATC.trimmed.uniq.MAPPED.chr1.sort.bed
/Library/Python/2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/usr/local/bin/clipper", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/usr/local/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 674, in call_main
    main(options)
  File "/usr/local/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 611, in main
    options.min_width)
  File "/usr/local/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 477, in filter_results
    peaks['transcriptome_poisson_p'] = peaks.apply(transcriptome_poissonP, axis=1) if use_global_cutoff else np.nan
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2357, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2422, in _set_item
    self._ensure_valid_index(value)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2404, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

```
Pandas version: 0.18.1

**Comment by gpratt** [comment]
That one I know :)

It means you didn't call any peaks.  How many reads does your test bam file
have?  I'm actually free to address some issues in clipper, this is one of
the ones that I'm going to try and take care of.



Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by gpratt** [comment]
I've fixed the issue with the latest commit to master on github.  Try it
out and see if it works for you.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by ShanSabri** [comment]
Yeah, this bam is less read abundant than others. Issue is fixed! Thank you!
