### ISSUE TITLE
keyerror with clipper (possibly pybedtools)

### ISSUE THREAD

**Issue by masonmlai** [YeoLab/clipper#45]
Here's the stack trace:

```
(clipper)[mason@ip-172-31-41-168 clipper]$ clipper -b haloclip_prokspen.chr1.hg19.star.bam -o haloclip_prokspen.chr1.hg19.clipper.bed -s hg19
Traceback (most recent call last):
  File "/storage/Users/mason/env/clipper/bin/clipper", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/storage/Users/mason/env/clipper/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 688, in call_main
    main(options)
  File "/storage/Users/mason/env/clipper/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 556, in main
    options.premRNA).saveas()
  File "/storage/Users/mason/env/clipper/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 183, in build_transcript_data_gtf_as_structure
    if "transcript_ids" in gene.attrs:
  File "cbedtools.pyx", line 76, in pybedtools.cbedtools.Attributes.__getitem__ (pybedtools/cbedtools.cpp:1888)
KeyError: 0
```

 and my virtualenv:

```
(clipper)[mason@ip-172-31-41-168 clipper]$ pip list
argparse (1.4.0)
clipper (0.2.0)
Cython (0.24.1)
HTSeq (0.6.1)
matplotlib (1.1.0)
numpy (1.7.1)
pandas (0.19.0)
pip (1.4.1)
pybedtools (0.5)
pysam (0.7.6)
python-dateutil (2.5.3)
pytz (2016.7)
scikit-learn (0.13)
scipy (0.11.0)
setuptools (0.9.8)
six (1.10.0)
wsgiref (0.1.2)
```

I didn't install clipper through pip, even though it's listed. I git-cloned the clipper repo and built it with `python setup.py install`.

**Comment by njaberi** [comment]
I'm having the exact same issue. Did you have any luck with this?
