### ISSUE TITLE
Clipper run error

### ISSUE THREAD

**Issue by nattifftoffe** [YeoLab/clipper#47]
Hi,
I am trying to run clipper in its simplest configuration 
`clipper -b /path/to/bamfile  -s hg19`

and I am getting the following error message

`Traceback (most recent call last):
  File "/afs/cats.ucsc.edu/users/r/juphilip/software/anaconda2/bin/clipper", line 11, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/afs/cats.ucsc.edu/users/r/juphilip/software/anaconda2/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 688, in call_main
    main(options)
  File "/afs/cats.ucsc.edu/users/r/juphilip/software/anaconda2/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 590, in main
    with multiprocessing.Pool(int(options.np)) as pool:
AttributeError: __exit__
`

I prepared the bam files as described in the wiki and I think I am using the latest version of clipper. What else could be the cause of this problem? I would really appreciate the help

Thank you so much in advance!

**Comment by noncodo** [comment]
You closed this issue, but there is no solution. I'm getting the same error, and would appreciate your guidance! I presume it is something silly...
