### ISSUE TITLE
OverflowError: can't convert negative value to CHRPOS

### ISSUE THREAD

**Issue by gk7279** [YeoLab/clipper#55]
**clipper -b mm10.bam --gtfFile mm10_UCSC_knownGene.UTR.gtf -o mm10.peaks.bed --bonferroni --superlocal --threshold-method binomial --save-pickle**

############

Traceback (most recent call last):
  File "/home/user666/.local/bin/clipper", line 11, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()

  File "/home/user666/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 687, in call_main
    main(options)

  File "/home/user666/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 544, in main
    gene_tool = build_transcript_data_gtf(pybedtools.BedTool(options.gtfFile), options.premRNA).saveas()

  File "/home/user666/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 255, in build_transcript_data_gtf
    "gene_id=" + gene['gene_id'] + "; transcript_id=" + gene['transcript_id'] + "; effective_length=" + str(effective_length)]))

  File "pybedtools/cbedtools.pyx", line 582, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:10027)

  File "pybedtools/cbedtools.pyx", line 687, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:9745)

OverflowError: can't convert negative value to CHRPOS

**Comment by gk7279** [comment]
Used gprat's suggestion of making a custom AS_STRUCTUREd gff file from #39. Fed it to clipper via --gtfFile option and there is absolutely nothing in the output file. Does that mean my data is at fault? I used tophat to align the reads. Any pointers? Thanks.

**Comment by algaebrown** [comment]
The current version `--gtfFile` is removed. Follow this wiki for additional genomes.
https://github.com/YeoLab/clipper/wiki/Supporting-additional-species
