### ISSUE TITLE
clipper -h failed

### ISSUE THREAD

**Issue by lmanchon** [YeoLab/clipper#69]
--Hi,

it failed with:

./clipper -h
./Traceback (most recent call last):
  File "./clipper", line 11, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/soft/CLIPPER/lib/python/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 17, in <module>
    from clipper.src.call_peak import call_peaks, poissonP
  File "/home/soft/CLIPPER/lib/python/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/call_peak.py", line 694, in <module>
    class MyGMM(mixture.GMM):
AttributeError: 'module' object has no attribute 'GMM'

how to fix that ?
thx

**Comment by sunhaifeng123** [comment]
pip install scikit-learn==0.18.2 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by Samashoon** [comment]
Hi, 
I get exactly the same error. "pip install scikit-learn==0.18.2 -i https://pypi.tuna.tsinghua.edu.cn/simple" didn't fix the error. 
Is there any other way to fix it?
Thanks

**Comment by cainbn97** [comment]
GMM was deprecated in scikit-learn==0.18. Installing scikit-learn=<0.17* should fix the problem.

[https://stackoverflow.com/questions/49375927/attributeerror-gmm-object-has-no-attribute-covariances-attributeerror/49376863#49376863](url)

I hope this helps!

**Comment by IrisWEI-1996** [comment]
I'm not sure if this will help but I figured it out with 'unset PYTHONPATH' in the virtual environment.

**Comment by algaebrown** [comment]
sci-kit learn dependency is solved in newer clipper release.
