### ISSUE TITLE
`clipper -h` fails after clean install

### ISSUE THREAD

**Issue by MattBrauer** [YeoLab/clipper#86]
```
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/opt/anaconda3/bin/clipper", line 5, in <module>
    from clipper.src.main import call_main
  File "/Users/mbrauer/maze/clipper/clipper/src/main.py", line 16, in <module>
    from clipper.src.call_peak import call_peaks
  File "/Users/mbrauer/maze/clipper/clipper/src/call_peak.py", line 28, in <module>
    from clipper.src.peaks import shuffle, find_sections
ImportError: dlopen(/Users/mbrauer/maze/clipper/clipper/src/peaks.so, 2): no suitable image found.  Did find:
	/Users/mbrauer/maze/clipper/clipper/src/peaks.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/mbrauer/maze/clipper/clipper/src/peaks.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

macos 10.15.6
Python 3.7.6

**Comment by MattBrauer** [comment]
It looks like `peaks.so` is architecture-dependent compiled code, which makes the application non-portable.

Can you include a makefile and the build process in the install procedure?

**Comment by algaebrown** [comment]
@mlovci @gpratt I googled a bit and it seems .so files are executable files built from .c. Correct me if I am wrong. I wonder do you have the original code? Thanks!

**Comment by gpratt** [comment]
I build this some files from cython.  Its fallen out of vogue now, but it
was how I got some important speed increases.


Gabriel Pratt

**Comment by algaebrown** [comment]
Which Cython file is it from? Is it from peaksmodule.cc? And how can I make it platform compatible?

thank you so much!

**Comment by gpratt** [comment]
yup,

As for how to make it platform compatible, I've got no idea.

Honestly you may have to re-write that code, not entirely sure how to fix
it these days.
Gabriel Pratt

**Comment by bakerwm** [comment]
> Which Cython file is it from? Is it from peaksmodule.cc? And how can I make it platform compatible?
> 
> thank you so much!

The file `peaks.so` might not work with `python3.x`;  (I cannot run the latest version `clipper v2.1.0`, on Ubuntu 18.04, Python 3.8)

```
$ cd clipper/src
$ python2
Python 2.7.18 (default, Mar  8 2021, 13:02:45)
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import peaks
>>> dir(peaks)
['__doc__', '__file__', '__name__', '__package__', 'find_sections', 'readsToWiggle_pysam', 'shuffle']

$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import peaks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_peaks)
```
