### ISSUE TITLE
pip install clipper --user

### ISSUE THREAD

**Issue by jalalsiddiqui** [YeoLab/clipper#92]
I installed clipper via pip install clipper however when I try to run it I get the following errors:

bash-4.2$ clipper
Traceback (most recent call last):
  File "/users/PAS1143/osu8165/.local/bin/clipper", line 5, in <module>
    from clipper.src.peakfinder import call_main
  File "/users/PAS1143/osu8165/.local/lib/python2.7/site-packages/clipper/src/peakfinder.py", line 16, in <module>
    import pybedtools
  File "/users/PAS1143/osu8165/python_lib/lib/python3.5/site-packages/pybedtools-0.8.1-py3.5-linux-x86_64.egg/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (
  File "/users/PAS1143/osu8165/python_lib/lib/python3.5/site-packages/pybedtools-0.8.1-py3.5-linux-x86_64.egg/pybedtools/cbedtools.py", line 7, in <module>
    __bootstrap__()
  File "/users/PAS1143/osu8165/python_lib/lib/python3.5/site-packages/pybedtools-0.8.1-py3.5-linux-x86_64.egg/pybedtools/cbedtools.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
ImportError: /users/PAS1143/osu8165/python_lib/lib/python3.5/site-packages/pybedtools-0.8.1-py3.5-linux-x86_64.egg/pybedtools/cbedtools.cpython-35m-x86_64-linux-gn
u.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E

**Comment by algaebrown** [comment]
Hi Jalal,
Sorry for the late reply
it seems to be a problem in versions of pybedtools.

https://github.com/daler/pybedtools/issues/302

can you recall how you solved the problem.

Thanks

**Comment by jalalsiddiqui** [comment]
I will check over my notes and get back to you
