### ISSUE TITLE
error on main.py

### ISSUE THREAD

**Issue by alexmondaini** [YeoLab/clipper#95]
My command:

```
  clipper \
    --species hg19 \
    --bam ~{call_peak_bam} \
    --save-pickle \
    --outfile ~{bed_peak_intervals}
```
using docker brianyee/clipper:5d865bb

```
WARNING:py.warnings:/opt/conda/envs/clipper3/lib/python3.7/site-packages/scipy/interpolate/fitpack2.py:253: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)

Traceback (most recent call last):
  File "/opt/conda/envs/clipper3/bin/clipper", line 33, in <module>
    sys.exit(load_entry_point('clipper==2.0.0', 'console_scripts', 'clipper')())
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.0.0-py3.7-linux-x86_64.egg/clipper/src/main.py", line 266, in call_main
    main(options)
  File "/opt/conda/envs/clipper3/lib/python3.7/site-packages/clipper-2.0.0-py3.7-linux-x86_64.egg/clipper/src/main.py", line 148, in main
    pickle.dump(peaks_dicts, file=f)
TypeError: write() argument must be str, not bytes
```

line 148 is:

```
    if options.save_pickle is True:
        with open(options.outfileF + ".pickle", 'w') as f:
            # TODO Can't pickle save after filtering ? as we have a tsv now, not a peaks_dicts list !?
            pickle.dump(peaks_dicts, file=f)

```

**Comment by byee4** [comment]
It looks like --save-pickle doesn't work quite right yet, can you try without that option?

**Comment by alexmondaini** [comment]
ok cool I try, read somewhere that in python you can pass the writing in bytes as such:
```

   if options.save_pickle is True:
        with open(options.outfileF + ".pickle", 'w') as f:
            # TODO Can't pickle save after filtering ? as we have a tsv now, not a peaks_dicts list !?
            pickle.dump(peaks_dicts, file=f)
```

maybe that would solve the bug.
